name: Copy Folder from Private Repo

on:
  workflow_dispatch:

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v3
        with:
          ref: master   # explicitly use master for gnuton-asuswrt-merlin.ng

      - name: Checkout source private repo
        uses: actions/checkout@v3
        with:
          repository: kornbred/asus-tuf-be3600-src
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main    # explicitly use main for asus-tuf-be3600-src
          path: src

      - name: Copy folder into destination
        run: |
          mkdir -p release
          rm -rf release/src-rt-5.04behnd.4916 || true
          cp -r src/release/src-rt-5.04behnd.4916 release/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add release/src-rt-5.04behnd.4916
          git commit -m "[skip ci] Copy src-rt-5.04behnd.4916 from private repo"
          git push
